server.port=8001

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/mdm_assignment_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=mySuperSecretKeyThatIsAtLeast256BitsLongForHMACSHA256Algorithm
jwt.expiration=86400000

spring.security.user.name=none
spring.security.user.password=none
logging.level.org.springframework.security=DEBUG